baseURL: "https://andreagemelli.me/"
title: ğŸ¤ŒğŸ» Andrea Gemelli
description: "This is my portfolio"
paginate: 5
theme: [PaperMod]
languageCode: en-us

enableEmoji: true

languages:
  en:
      languageName: "english"
      weight: 1
      taxonomies:
        category: categories
        tag: tags
        series: series
        
      menu:
        main:
          - name: About me
            url: about
            weight: 5
          - name: Publications
            url: publications
            weight: 10
          - name: AI Notes
            url: archives
            weight: 15
            
      params:
        languageAltTitle: English
      

params:

  description: "My Portfolio"
  author: Andrea Gemelli
  defaultTheme: auto # to switch between dark or light according to browser theme
  displayFullLangName: true
  ShowShareButtons: true
  env: production

  profileMode:
    enabled: true
    title: "Nice to meet you! ğŸ¤—" # optional default will be site title
    subtitle: "PhD ğŸ“š | AI/ML Scientist ğŸ¤“ | Dev ğŸ‘¨ğŸ»â€ğŸ’» | Musician ğŸ¸ | Nerd ğŸ®"
    imageUrl: "img/me.jpg" # optional
    imageTitle: "ğŸ¤ŒğŸ»" # optional
    imageWidth: 300 # custom size
    imageHeight: 300 # custom size

  socialIcons: # optional
    - name: "email"
      url: "gemelli.andrea@hotmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/andrea-gemelli/"
    - name: "github"
      url: "https://github.com/andreagemelli"
    - name: "x"
      url: "https://twitter.com/_andreagemelli"
    - name: "scholar"
      url: "http://tiny.cc/myscholar"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
    
    

  
